openapi: 3.0.0
info:
  title: Rest co_es
  version: '1.0'
servers:
  - url: 'https://test.placetopay.com/'
    description: Modo Pruebas
paths:
  /rest/gateway/query:
    post:
      summary: ''
      operationId: post-rest-gateway-query
      responses:
        '200':
          description: OK
  /rest/gateway/information:
    post:
      summary: Solicitud de Información
      operationId: post-rest-gateway-information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      status:
                        type: string
                        minLength: 1
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                        minLength: 1
                      date:
                        type: string
                        minLength: 1
                    required:
                      - status
                      - reason
                      - message
                      - date
                  provider:
                    type: string
                    minLength: 1
                  serviceCode:
                    type: string
                    minLength: 1
                  cardType:
                    type: string
                    minLength: 1
                  cardTypes:
                    type: array
                    items:
                      required: []
                      properties: {}
                  displayInterest:
                    type: boolean
                  requireOtp:
                    type: boolean
                  requireCvv2:
                    type: boolean
                  threeDS:
                    type: string
                    minLength: 1
                  credits:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - description
                        - code
                        - groupCode
                        - type
                      properties:
                        description:
                          type: string
                          minLength: 1
                        code:
                          type: string
                          minLength: 1
                        groupCode:
                          type: string
                          minLength: 1
                        type:
                          type: string
                          minLength: 1
                        installments:
                          type: array
                          items:
                            required: []
                            properties: {}
                required:
                  - status
                  - provider
                  - serviceCode
                  - cardType
                  - cardTypes
                  - displayInterest
                  - requireOtp
                  - requireCvv2
                  - threeDS
                  - credits
              examples:
                Ejemplo:
                  value:
                    status:
                      status: OK
                      reason: '00'
                      message: La petición se ha procesado correctamente
                      date: '2021-03-02T11:04:16-05:00'
                    provider: CREDIBANCO
                    serviceCode: CR_VS
                    cardType: C
                    cardTypes:
                      - C
                      - R
                      - A
                    displayInterest: false
                    requireOtp: false
                    requireCvv2: true
                    threeDS: unsupported
                    credits:
                      - description: Cuotas
                        code: '0'
                        groupCode: C
                        type: '00'
                        installments:
                          - 1
                          - 2
                          - 3
                          - 4
                          - 5
                          - 6
                          - 7
                          - 8
                          - 9
                          - 10
                          - 11
                          - 12
                          - 13
                          - 14
                          - 15
                          - 16
                          - 17
                          - 18
                          - 19
                          - 20
                          - 21
                          - 22
                          - 23
                          - 24
                          - 25
                          - 26
                          - 27
                          - 28
                          - 29
                          - 30
                          - 31
                          - 32
                          - 33
                          - 34
                          - 35
                          - 36
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    login:
                      type: string
                      minLength: 1
                    tranKey:
                      type: string
                      minLength: 1
                    nonce:
                      type: string
                      minLength: 1
                    seed:
                      type: string
                      minLength: 1
                  required:
                    - login
                    - tranKey
                    - nonce
                    - seed
                instrument:
                  type: object
                  properties:
                    card:
                      type: object
                      properties:
                        number:
                          type: string
                          minLength: 1
                      required:
                        - number
                  required:
                    - card
                payment:
                  type: object
                  properties:
                    reference:
                      type: string
                      minLength: 1
                    amount:
                      type: object
                      properties:
                        total:
                          type: number
                        currency:
                          type: string
                          minLength: 1
                      required:
                        - total
                        - currency
                  required:
                    - reference
                    - amount
              required:
                - auth
                - instrument
                - payment
            examples:
              Ejemplo:
                value:
                  auth:
                    login: 6dd490faf9cb87a9862245da41170ff2
                    tranKey: JUfKi8+W//kX43WZd8FcnNsdl7zkaeAQdmSOudWcVi0=
                    nonce: MzgwYWYwMjc2ZWUzODA5YmI1MDQ1YmNjYzdlNzY1MTY=
                    seed: '2021-03-02T17:03:50+01:00'
                  instrument:
                    card:
                      number: '4111111111111111'
                  payment:
                    reference: testing_12
                    amount:
                      total: 1000
                      currency: COP
  /rest/gateway/process:
    post:
      summary: ''
      operationId: post-rest-gateway-process
      responses:
        '200':
          description: OK
      description: ''
  /gateway/process/:
    post:
      summary: Cobrar Tokenizacion
      operationId: post-gateway-process
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      status:
                        type: string
                        minLength: 1
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                        minLength: 1
                      date:
                        type: string
                        minLength: 1
                    required:
                      - status
                      - reason
                      - message
                      - date
                  date:
                    type: string
                    minLength: 1
                  transactionDate:
                    type: string
                    minLength: 1
                  internalReference:
                    type: number
                  reference:
                    type: string
                    minLength: 1
                  paymentMethod:
                    type: string
                    minLength: 1
                  franchise:
                    type: string
                    minLength: 1
                  franchiseName:
                    type: string
                    minLength: 1
                  issuerName:
                    type: string
                    minLength: 1
                  amount:
                    type: object
                    properties:
                      currency:
                        type: string
                        minLength: 1
                      total:
                        type: number
                    required:
                      - currency
                      - total
                  conversion:
                    type: object
                    properties:
                      from:
                        type: object
                        properties:
                          currency:
                            type: string
                            minLength: 1
                          total:
                            type: number
                        required:
                          - currency
                          - total
                      to:
                        type: object
                        properties:
                          currency:
                            type: string
                            minLength: 1
                          total:
                            type: number
                        required:
                          - currency
                          - total
                      factor:
                        type: number
                    required:
                      - from
                      - to
                      - factor
                  authorization:
                    type: string
                    minLength: 1
                  receipt:
                    type: number
                  type:
                    type: string
                    minLength: 1
                  refunded:
                    type: boolean
                  lastDigits:
                    type: string
                    minLength: 1
                  provider:
                    type: string
                    minLength: 1
                  discount: {}
                  processorFields:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      b24:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - b24
                  additional:
                    type: object
                    properties:
                      merchantCode:
                        type: string
                        minLength: 1
                      terminalNumber:
                        type: string
                        minLength: 1
                      bin:
                        type: string
                        minLength: 1
                      expiration:
                        type: string
                        minLength: 1
                      installments:
                        type: string
                        minLength: 1
                    required:
                      - merchantCode
                      - terminalNumber
                      - bin
                      - expiration
                      - installments
                required:
                  - status
                  - date
                  - transactionDate
                  - internalReference
                  - reference
                  - paymentMethod
                  - franchise
                  - franchiseName
                  - issuerName
                  - amount
                  - conversion
                  - authorization
                  - receipt
                  - type
                  - refunded
                  - lastDigits
                  - provider
                  - processorFields
                  - additional
              examples:
                Ejemplo:
                  value:
                    status:
                      status: APPROVED
                      reason: '00'
                      message: Aprobada
                      date: '2021-03-02T11:47:04-05:00'
                    date: '2021-03-02T11:47:04-05:00'
                    transactionDate: '2021-03-02T11:47:04-05:00'
                    internalReference: 1505728229
                    reference: TEST_20171108_144400
                    paymentMethod: CR_VS
                    franchise: visa
                    franchiseName: Visa
                    issuerName: 'JPMORGAN CHASE BANK, N.A.'
                    amount:
                      currency: COP
                      total: 1000
                    conversion:
                      from:
                        currency: COP
                        total: 1000
                      to:
                        currency: COP
                        total: 1000
                      factor: 1
                    authorization: '999999'
                    receipt: 1020330770
                    type: AUTH_ONLY
                    refunded: false
                    lastDigits: '****1111'
                    provider: CREDIBANCO
                    discount: null
                    processorFields:
                      id: c3e5a278db727933e12796139cdbf506
                      b24: '000'
                    additional:
                      merchantCode: '011271442'
                      terminalNumber: '00057742'
                      bin: '411111'
                      expiration: '0222'
                      installments: '1'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    login:
                      type: string
                      minLength: 1
                    tranKey:
                      type: string
                      minLength: 1
                    nonce:
                      type: string
                      minLength: 1
                    seed:
                      type: string
                      minLength: 1
                  required:
                    - login
                    - tranKey
                    - nonce
                    - seed
                locale:
                  type: string
                  minLength: 1
                payment:
                  type: object
                  properties:
                    reference:
                      type: string
                      minLength: 1
                    description:
                      type: string
                      minLength: 1
                    amount:
                      type: object
                      properties:
                        currency:
                          type: string
                          minLength: 1
                        total:
                          type: number
                      required:
                        - currency
                        - total
                  required:
                    - reference
                    - description
                    - amount
                ipAddress:
                  type: string
                  minLength: 1
                userAgent:
                  type: string
                  minLength: 1
                instrument:
                  type: object
                  properties:
                    token:
                      type: object
                      properties:
                        token:
                          type: string
                          minLength: 1
                        subtoken:
                          type: string
                          minLength: 1
                        franchise:
                          type: string
                          minLength: 1
                        franchiseName:
                          type: string
                          minLength: 1
                        issuerName:
                          type: string
                          minLength: 1
                        lastDigits:
                          type: string
                          minLength: 1
                        validUntil:
                          type: string
                          minLength: 1
                      required:
                        - token
                        - subtoken
                        - franchise
                        - franchiseName
                        - issuerName
                        - lastDigits
                        - validUntil
                    credit:
                      type: object
                      properties:
                        code:
                          type: string
                          minLength: 1
                        type:
                          type: string
                          minLength: 1
                        groupCode:
                          type: string
                          minLength: 1
                        installment:
                          type: string
                          minLength: 1
                      required:
                        - code
                        - type
                        - groupCode
                        - installment
                  required:
                    - token
                    - credit
                payer:
                  type: object
                  properties:
                    document:
                      type: string
                      minLength: 1
                    documentType:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    surname:
                      type: string
                      minLength: 1
                    email:
                      type: string
                      minLength: 1
                    mobile:
                      type: string
                      minLength: 1
                  required:
                    - document
                    - documentType
                    - name
                    - surname
                    - email
                    - mobile
                buyer:
                  type: object
                  properties:
                    document:
                      type: string
                      minLength: 1
                    documentType:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    surname:
                      type: string
                      minLength: 1
                    email:
                      type: string
                      minLength: 1
                    mobile:
                      type: string
                      minLength: 1
                  required:
                    - document
                    - documentType
                    - name
                    - surname
                    - email
                    - mobile
              required:
                - auth
                - locale
                - payment
                - ipAddress
                - userAgent
                - instrument
                - payer
                - buyer
            examples:
              Ejemplo:
                value:
                  auth:
                    login: 6dd490faf9cb87a9862245da41170ff2
                    tranKey: Lz3OSXV58JePuY0b/bXmxzg2Ee4/8jSCU9s7Kqwm9SQ=
                    nonce: NGUwNWVmMzAxZDhhZjY0N2M4YTdmYmUwNjU1NTA1NzQ=
                    seed: '2021-03-02T17:46:46+01:00'
                  locale: es_CO
                  payment:
                    reference: TEST_20171108_144400
                    description: Prueba rest colombia.
                    amount:
                      currency: COP
                      total: 1000
                  ipAddress: 127.0.0.1
                  userAgent: Mozilla/5.0 USER_AGENT HERE
                  instrument:
                    token:
                      token: bd8663e5f5635ff6e84e39171978de3aac5fb4cdf16b9c78ba1f8d9d049c86d2
                      subtoken: '9684994211631111'
                      franchise: visa
                      franchiseName: Visa
                      issuerName: 'JPMORGAN CHASE BANK, N.A.'
                      lastDigits: '1111'
                      validUntil: '2022-02-28'
                    credit:
                      code: '0'
                      type: '00'
                      groupCode: C
                      installment: '1'
                  payer:
                    document: '8467451900'
                    documentType: CC
                    name: Miss Delia Schamberger Sr.
                    surname: Wisozk
                    email: tesst@gmail.com
                    mobile: '3006108300'
                  buyer:
                    document: '8467451900'
                    documentType: CC
                    name: Miss Delia Schamberger Sr.
                    surname: Wisozk
                    email: tesst@gmail.com
                    mobile: '3006108300'
  /gateway/process:
    post:
      summary: Procesamiento de transacción
      operationId: post-gateway-process
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      status:
                        type: string
                        minLength: 1
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                        minLength: 1
                      date:
                        type: string
                        minLength: 1
                    required:
                      - status
                      - reason
                      - message
                      - date
                  date:
                    type: string
                    minLength: 1
                  transactionDate:
                    type: string
                    minLength: 1
                  internalReference:
                    type: number
                  reference:
                    type: string
                    minLength: 1
                  paymentMethod:
                    type: string
                    minLength: 1
                  franchise:
                    type: string
                    minLength: 1
                  franchiseName:
                    type: string
                    minLength: 1
                  issuerName:
                    type: string
                    minLength: 1
                  amount:
                    type: object
                    properties:
                      currency:
                        type: string
                        minLength: 1
                      total:
                        type: number
                    required:
                      - currency
                      - total
                  conversion:
                    type: object
                    properties:
                      from:
                        type: object
                        properties:
                          currency:
                            type: string
                            minLength: 1
                          total:
                            type: number
                        required:
                          - currency
                          - total
                      to:
                        type: object
                        properties:
                          currency:
                            type: string
                            minLength: 1
                          total:
                            type: number
                        required:
                          - currency
                          - total
                      factor:
                        type: number
                    required:
                      - from
                      - to
                      - factor
                  authorization:
                    type: string
                    minLength: 1
                  receipt:
                    type: number
                  type:
                    type: string
                    minLength: 1
                  refunded:
                    type: boolean
                  lastDigits:
                    type: string
                    minLength: 1
                  provider:
                    type: string
                    minLength: 1
                  discount: {}
                  processorFields:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      b24:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - b24
                  additional:
                    type: object
                    properties:
                      merchantCode:
                        type: string
                        minLength: 1
                      terminalNumber:
                        type: string
                        minLength: 1
                      bin:
                        type: string
                        minLength: 1
                      expiration:
                        type: string
                        minLength: 1
                      installments:
                        type: string
                        minLength: 1
                    required:
                      - merchantCode
                      - terminalNumber
                      - bin
                      - expiration
                      - installments
                required:
                  - status
                  - date
                  - transactionDate
                  - internalReference
                  - reference
                  - paymentMethod
                  - franchise
                  - franchiseName
                  - issuerName
                  - amount
                  - conversion
                  - authorization
                  - receipt
                  - type
                  - refunded
                  - lastDigits
                  - provider
                  - processorFields
                  - additional
              examples:
                Ejemplo:
                  value:
                    status:
                      status: APPROVED
                      reason: '00'
                      message: Aprobada
                      date: '2021-03-02T11:47:04-05:00'
                    date: '2021-03-02T11:47:04-05:00'
                    transactionDate: '2021-03-02T11:47:04-05:00'
                    internalReference: 1505728229
                    reference: TEST_20171108_144400
                    paymentMethod: CR_VS
                    franchise: visa
                    franchiseName: Visa
                    issuerName: 'JPMORGAN CHASE BANK, N.A.'
                    amount:
                      currency: COP
                      total: 1000
                    conversion:
                      from:
                        currency: COP
                        total: 1000
                      to:
                        currency: COP
                        total: 1000
                      factor: 1
                    authorization: '999999'
                    receipt: 1020330770
                    type: AUTH_ONLY
                    refunded: false
                    lastDigits: '****1111'
                    provider: CREDIBANCO
                    discount: null
                    processorFields:
                      id: c3e5a278db727933e12796139cdbf506
                      b24: '000'
                    additional:
                      merchantCode: '011271442'
                      terminalNumber: '00057742'
                      bin: '411111'
                      expiration: '0222'
                      installments: '1'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    login:
                      type: string
                    tranKey:
                      type: string
                    nonce:
                      type: string
                    seed:
                      type: string
                locale:
                  type: string
                payment:
                  type: object
                  properties:
                    reference:
                      type: string
                    description:
                      type: string
                    amount:
                      type: object
                      properties:
                        currency:
                          type: string
                        total:
                          type: number
                ipAddress:
                  type: string
                userAgent:
                  type: string
                instrument:
                  type: object
                  properties:
                    card:
                      type: object
                      properties:
                        number:
                          type: number
                        expirationMonth:
                          type: number
                        expirationYear:
                          type: number
                        cvv:
                          type: number
                    credit:
                      type: object
                      properties:
                        code:
                          type: number
                        type:
                          type: number
                        groupCode:
                          type: string
                        installment:
                          type: number
                payer:
                  type: object
                  properties:
                    document:
                      type: number
                    documentType:
                      type: string
                    name:
                      type: string
                    surname:
                      type: string
                    email:
                      type: string
                    mobile:
                      type: string
                buyer:
                  type: object
                  properties:
                    document:
                      type: number
                    documentType:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    '':
                      type: string
            examples:
              Ejemplo:
                value:
                  auth:
                    login: 6dd490faf9cb87a9862245da41170ff2
                    tranKey: JUfKi8+W//kX43WZd8FcnNsdl7zkaeAQdmSOudWcVi0=
                    nonce: MzgwYWYwMjc2ZWUzODA5YmI1MDQ1YmNjYzdlNzY1MTY=
                    seed: '2021-03-02T17:03:50+01:00'
                  locale: es_CO
                  payment:
                    reference: TEST_20171108_144400
                    description: Prueba rest colombia.
                    amount:
                      currency: COP
                      total: 1000
                  ipAddress: 127.0.0.1
                  userAgent: Mozilla/5.0 USER_AGENT HERE
                  instrument:
                    card:
                      number: '4111111111111111'
                      expirationMonth: '12'
                      expirationYear: '22'
                      cvv: '123'
                    credit:
                      code: '0'
                      type: '00'
                      groupCode: C
                      installment: '1'
                  payer:
                    document: '8467451900'
                    documentType: CC
                    name: Miss Delia Schamberger Sr.
                    surname: Wisozk
                    email: tesst@gmail.com
                    mobile: '3006108300'
                  buyer:
                    document: '8467451900'
                    documentType: CC
                    name: Miss Delia Schamberger Sr.
                    surname: Wisozk
                    email: tesst@gmail.com
                    mobile: '3006108300'
components:
  schemas: {}
